name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm build
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist  # Update this to your actual build output folder
          clean: true  # Optional: clean the existing contents of the gh-pages branch
